### ISSUE TITLE
Settings file

### ISSUE THREAD

**Issue by JCKodel** [Genymobile/scrcpy#4864]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

Just opened this issue to thanks the developer for the amazing piece of software. As a Flutter developer, this is wonderful.

But, I have to complain about something, after all, it's github issues... lemme think...

**Is your feature request related to a problem? Please describe.**
I made a .bat file to open the window at a specific location and specific size (bottom left corner of my second monitor, with 100% resolution rate (something Android Emulator cannot do, it always open whenever it wants)). Problem is: a console window is kept open running scrcpy.

**Describe the solution you'd like**
An extra .exe or maybe even the same scrcpy.exe that shows no terminal window and it reads its configuration from a `scrcpy.yml` file in the user folder.

For example:

`%USERPROFILE%\scrcpy.yml`
```yml
no-audio: true
no-audio-playback: true
power-off-on-close: true
window-borderless: true
window-x: 3840
window-y: 466
window-width: 720
window-height: 1600
```

A simple double-click on `scrcpy.exe`, it just open with those settings, with no terminal window.
```
