### ISSUE TITLE
How to update Windows packages

### ISSUE THREAD

**Issue by uvwild** [Genymobile/scrcpy#5397]
Being a devops guy and having new machines I find myself scripting my system installation.
On dumb windows11 this is a big challenge.
We are making progress, but regarding versions available on the package manager repos there is a big lack.

I would like to contribute if I can. 

How is this currently handled? 
Can I get a head start please?

**Comment by cutebunnygaming10** [comment]
This is unrelated to scrcpy?

**Comment by cutebunnygaming10** [comment]
If you are asking about how does it work its the power of the internet

**Comment by uvwild** [comment]
Let me help you understand how to add a package version to the Windows Package Manager (winget) repository. I'll provide guidance on submitting a new package version to the Windows Package Manager Community Repository.





# Adding a Package Version to Windows Package Manager (winget)

## Prerequisites
- A GitHub account
- Git installed on your system
- The package you want to submit meets [Microsoft's requirements](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md)

## Step-by-Step Process

### 1. Fork the Repository
1. Go to https://github.com/microsoft/winget-pkgs
2. Click the "Fork" button in the top-right corner
3. Clone your fork locally:
```bash
git clone https://github.com/YOUR-USERNAME/winget-pkgs.git
cd winget-pkgs
```

### 2. Create the Package Manifest
1. Navigate to the correct directory structure:
```bash
cd manifests/<first-letter-of-publisher>/<publisher>/<package-name>
```

2. Create a new directory for your version:
```bash
mkdir <version>
```

3. Create the manifest file(s). For single-file manifests:
```yaml
# <package-name>.yaml
PackageIdentifier: Publisher.AppName
PackageVersion: "x.y.z"
PackageName: Application Name
Publisher: Publisher Name
License: License
ShortDescription: Short description of the application
PackageUrl: https://example.com
Installers:
  - Architecture: x64
    InstallerType: msi # or exe, msix, etc.
    InstallerUrl: https://example.com/download/app-x64.msi
    InstallerSha256: CALCULATED-SHA256-HASH
    ProductCode: "{PRODUCT-CODE}" # For MSI installers
ManifestType: singleton
ManifestVersion: 1.4.0
```

### 3. Validate the Manifest
1. Install winget-create tool:
```powershell
winget install Microsoft.WingetCreate
```

2. Validate your manifest:
```powershell
winget-create validate <path-to-manifest>
```

### 4. Submit the Package
1. Create a new branch:
```bash
git checkout -b add-<package-name>-<version>
```

2. Add and commit your changes:
```bash
git add .
git commit -m "Add <package-name> version <version>"
```

3. Push to your fork:
```bash
git push origin add-<package-name>-<version>
```

4. Create a Pull Request:
   - Go to your fork on GitHub
   - Click "Pull Request"
   - Select your branch
   - Fill in the PR template
   - Submit the PR

### 5. Automated Validation
- Wait for the automated validation to complete
- Address any issues raised by the validation
- Wait for review from the winget team

## Best Practices
1. Use semantic versioning for package versions
2. Always verify installer SHA256 hashes
3. Test the manifest locally before submitting
4. Keep descriptions concise and accurate
5. Include all required manifest fields

## Common Issues and Solutions
- **Invalid SHA256**: Recalculate using:
  ```powershell
  Get-FileHash <installer-path> -Algorithm SHA256
  ```
- **Product Code Missing**: For MSI installers, extract using:
  ```powershell
  Get-MSIProperty <installer-path> ProductCode
  ```
- **Version Format**: Use semantic versioning (x.y.z)
- **Invalid URLs**: Ensure URLs are direct download links


I've created a comprehensive guide for adding a package version to the Windows Package Manager repository. The guide covers everything from prerequisites to common issues you might encounter.

Would you like me to clarify any specific part of the process? I can provide more details about manifest validation, troubleshooting, or any other aspect of the submission process.
