### ISSUE TITLE
Auto-publish to winget on every release via winget-releaser Github Action workflow

### ISSUE THREAD

**Issue by jo-chemla** [Genymobile/scrcpy#5479]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

Some similar but vague requests here https://github.com/Genymobile/scrcpy/issues/3254 and there https://github.com/Genymobile/scrcpy/issues/5397 - if you'd like to close that new feature request to switch to the above mentioned issues, don't hesitate!

**Is your feature request related to a problem? Please describe.**
It would be useful to auto-update the `Genymobile.scrcpy` winget package, to always have the most up-to-date version of scrcpy when doing `winget install scrcpy`

**Describe the solution you'd like**
Here is a reference article based on [Winget-Releaser@v2 Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-). Below is an action yml files made to keep the winget package up-to-date on every github release, via Github Actions. 

Requires:
 - You will need to create a classic Personal Access Token (PAT) with public_repo scope.
 - This token should be added as a repository secret by creating a [new repo secret](https://github.com/Jacalz/rymdport/settings/secrets/actions/new) with name WINGET_ACC_TOKEN and value the token
 - Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Genymobile.scrcpy
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: 'scrcpy\-win64\-\w*\.zip$' 
```

**Describe alternatives you've considered**
We can still follow the current flow, where a user has to manually push a package update to [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo via a utility like [Komac](https://github.com/russellbanks/Komac).
